---
- name: Download cni
  get_url:
    url: "http://{{ hostvars['static'].ansible_host }}:{{static.port}}/cni-plugins/{{ cni_ver }}/cni-plugins-linux-amd64-{{ cni_ver }}.tgz"
    dest: "/tmp"
  tags: install_cni

- name: Create docker directories
  file: 
    path: "{{item}}"
    state: directory
  with_items:
    - "/etc/cni/net.d"
    - "/opt/cni/bin"
  tags: install_cni

- name: "Install cni"
  unarchive:
    src: "/tmp/cni-plugins-linux-amd64-{{ cni_ver }}.tgz"
    dest: /opt/cni/bin/
    owner: root
    group: root
    mode: 0755
    remote_src: yes
    # extra_opts:
    #   - --strip-components=1
  tags: install_cni