---
- name: "Download helm"
  unarchive:
    src: "http://{{ hostvars['static'].ansible_host }}:{{static.port}}/helm/{{helm_ver}}/helm-{{ helm_ver }}-linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    extra_opts:
      - --strip-components=1
  tags: install_helm

- name: "install helm binary files"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ bindest }}"
    remote_src: yes
    mode: '0755'
  with_items:
    - { src: "/tmp/helm" }