- hosts: "{{ run | default('kube_node')}}"
  gather_facts: true
  roles:
    - verify
    - system
    - package
    - kube-inflate
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-ha
    - cni
    - role: docker
      when: cri == "docker"
    - role: cri-dockerd
      when: ( cri == "docker" ) and ( KUBE_VER|float >=1.24 )
    - role: buildkit
      when: cri == "containerd"
    - role: containerd
      when: cri == "containerd"
    - role: nerdctl
      when: cri == "containerd"
    - role: cri-o
      when: cri == "cri-o"
    - kube-inflate
    - role: kube-ha
      when: kubernetes.lb.keepalived == false
    - kubelet
    - kube-proxy

- hosts: "{{ run | default('master-1')}}"
  gather_facts: false
  tasks:
  - name: "deploy auto-approve"
    shell: |
      cat <<EOF | kubectl apply -f -
      ---
      # enable bootstrapping nodes to create CSR
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: create-csrs-for-bootstrapping
      subjects:
      - kind: Group
        name: system:bootstrappers
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: system:node-bootstrapper
        apiGroup: rbac.authorization.k8s.io
      EOF

      cat <<EOF | kubectl apply -f -
      # Approve all CSRs for the group "system:bootstrappers"
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: auto-approve-csrs-for-group
      subjects:
      - kind: Group
        name: system:bootstrappers
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: system:certificates.k8s.io:certificatesigningrequests:nodeclient
        apiGroup: rbac.authorization.k8s.io
      EOF

      cat <<EOF | kubectl apply -f -
      # Approve renewal CSRs for the group "system:nodes"
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: auto-approve-renewals-for-nodes
      subjects:
      - kind: Group
        name: system:nodes
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: system:certificates.k8s.io:certificatesigningrequests:selfnodeclient
        apiGroup: rbac.authorization.k8s.io
      EOF