---
- name: Check that the encryption-config.yaml exists
  stat:
    path: "{{ static.certs.path }}/encryption-config.yaml"
  register: stat_result

- name: create encryption key
  shell: head -c 32 /dev/urandom | base64
  register: encryption_key
  when: stat_result.stat.exists == False

- name: ensure folder exist
  file:
    path: "{{ static.certs.path }}"
    state: directory
    mode: 0755
  when: stat_result.stat.exists == False

- name: create encryption config
  template:
    src: encryption-config.yaml.j2
    dest: "{{ static.certs.path }}/encryption-config.yaml"
  when: stat_result.stat.exists == False