---
- name: "Install keepalived"
  package:
    name:
      - keepalived
    state: present
    update_cache: yes
  tags: install_keepalived

- name: Create keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: Create check_apiserver.sh
  template:
    src: check_apiserver.sh.j2
    dest: /etc/keepalived/check_apiserver.sh

- name: Enable keepalived
  systemd:
    name: keepalived
    state: started
    enabled: yes
    daemon_reload: yes