---
- include_tasks: keepalived.yml
  when: kubernetes.lb.keepalived is true

- include_tasks: haproxy.yml
  when: kubernetes.lb.mode == "haproxy"

- include_tasks: nginx.yml
  when: kubernetes.lb.mode == "nginx"

- include_tasks: traefik.yml
  when: kubernetes.lb.mode == "traefik"

- include_tasks: lvscare.yml
  when: kubernetes.lb.mode == "lvscare"

- include_tasks: goproxy.yml
  when: kubernetes.lb.mode == "goproxy"