---
# - name: Disable traefik
#   systemd:
#     name: traefik
#     state: stopped
#     enabled: no
#     daemon_reload: yes
# - name: Disable haproxy
#   systemd:
#     name: haproxy
#     state: stopped
#     enabled: no
#     daemon_reload: yes
- name: "Generate nginx configure"
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"

- name: Set repo if Alpine
  ansible.builtin.set_fact:
    version: =1.22.0-r1
  when: ansible_facts['os_family'] == "Alpine"
- name: Set repo if Debian
  ansible.builtin.set_fact:
    version: =1.22.0-1~{{ ansible_facts['distribution_release'] }}
  when: ansible_facts['os_family'] == "Debian"
- name: Set repo if Red Hat
  ansible.builtin.set_fact:
    version: -1.22.0-1.{{ (ansible_facts['distribution'] == "Amazon") | ternary('amzn2', ('el' + ansible_facts['distribution_major_version'] | string)) }}.ngx
  when: ansible_facts['os_family'] == "RedHat"
- name: Set repo if SLES
  ansible.builtin.set_fact:
    version: =1.22.0-1.sles{{ ansible_facts['distribution_major_version'] }}.ngx
  when: ansible_facts['os_family'] == "Suse"
- name: Install NGINX
  ansible.builtin.include_role:
    name: ansible-role-nginx
  vars:
    nginx_version: "{{ version }}"
    nginx_service_modify: true
    nginx_service_timeout: 95
    nginx_branch: stable
    # nginx_logrotate_conf_enable: true
    # nginx_logrotate_conf:
    #   paths:
    #     - /var/log/nginx/*.log
    #   options:
    #     - daily
    #     - missingok
    #     - rotate 14
    #     - compress
    #     - delaycompress
    #     - notifempty
    #     - sharedscripts
- name: Enable nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes